<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.*" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.15.*" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WeatherRoute.Infrastructure\WeatherRoute.Infrastructure.csproj" />
    <ProjectReference Include="..\WeatherRoute.Application\WeatherRoute.Application.csproj" />
    <ProjectReference Include="..\WeatherRoute.Domain\WeatherRoute.Domain.csproj" />
  </ItemGroup>
</Project>