<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WeatherRoute.Application\WeatherRoute.Application.csproj" />
    <ProjectReference Include="..\WeatherRoute.Domain\WeatherRoute.Domain.csproj" />
  </ItemGroup>
</Project>